region: ap-northeast-1

function_name: notify-cloudtrail-events
handler: service.handler
role: lambda-iam_readonly+cloudtrail_readonly
description: notify-cloudtrail-events

aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 15
memory_size: 256
